### PR TITLE
Refactor: initial stage audit.ubq.fi

### PR DESCRIPTION
**Pull request by molecula451**
Resolves #171

### CODE REVIEW

**Comment by molecula451** [comment]
Continuous [deployments](https://github.com/ubiquity/audit.ubq.fi/pull/1#issuecomment-1972195639) looks good, looks like spell check [run](https://github.com/ubiquity/audit.ubq.fi/actions/runs/8105655004/job/22154316944?pr=1) it's failing because of the actual .cspell on "development" branch altho it is being commited [here](https://github.com/ubiquity/audit.ubq.fi/pull/1/commits/6983ab3f0e3980a1a24a0b485abfc7b480507361)

**Review by 0x4007 — APPROVED** [review]
Passed CI and deploy link looks fine.

**Review by gentlementlegen — APPROVED** [review]
I am fine with the changes too. Will just complain about the commit messages and the lack of tests.

**Comment by molecula451** [comment]
>  Will just complain about the commit messages 

Taking that in count

> and the lack of tests.

good for new upcoming issues

**Review by rndquu — APPROVED** [review]

**Pull request merged**
